# Generated by cpp4r: do not edit by hand

cpp4r_add_vec_for_ <- function(x, num) {
  .Call(`_cpp4rtest_cpp4r_add_vec_for_`, x, num)
}

data_frame_ <- function() {
  .Call(`_cpp4rtest_data_frame_`)
}

my_stop_n1fmt <- function(mystring) {
  invisible(.Call(`_cpp4rtest_my_stop_n1fmt`, mystring))
}

my_stop_n2fmt <- function(mystring, myarg) {
  invisible(.Call(`_cpp4rtest_my_stop_n2fmt`, mystring, myarg))
}

my_warning_n1fmt <- function(mystring) {
  invisible(.Call(`_cpp4rtest_my_warning_n1fmt`, mystring))
}

my_warning_n2fmt <- function(mystring, myarg) {
  invisible(.Call(`_cpp4rtest_my_warning_n2fmt`, mystring, myarg))
}

my_message_n1fmt <- function(mystring) {
  invisible(.Call(`_cpp4rtest_my_message_n1fmt`, mystring))
}

my_message_n2fmt <- function(mystring, myarg) {
  invisible(.Call(`_cpp4rtest_my_message_n2fmt`, mystring, myarg))
}

my_stop <- function(mystring, myarg) {
  invisible(.Call(`_cpp4rtest_my_stop`, mystring, myarg))
}

my_stop_n1 <- function(mystring) {
  invisible(.Call(`_cpp4rtest_my_stop_n1`, mystring))
}

my_warning <- function(mystring, myarg) {
  invisible(.Call(`_cpp4rtest_my_warning`, mystring, myarg))
}

my_warning_n1 <- function(mystring) {
  invisible(.Call(`_cpp4rtest_my_warning_n1`, mystring))
}

my_message <- function(mystring, myarg) {
  invisible(.Call(`_cpp4rtest_my_message`, mystring, myarg))
}

my_message_n1 <- function(mystring) {
  invisible(.Call(`_cpp4rtest_my_message_n1`, mystring))
}

remove_altrep <- function(x) {
  .Call(`_cpp4rtest_remove_altrep`, x)
}

upper_bound <- function(x, breaks) {
  .Call(`_cpp4rtest_upper_bound`, x, breaks)
}

findInterval2 <- function(x, breaks) {
  .Call(`_cpp4rtest_findInterval2`, x, breaks)
}

findInterval2_5 <- function(x, breaks) {
  .Call(`_cpp4rtest_findInterval2_5`, x, breaks)
}

findInterval3 <- function(x, breaks) {
  .Call(`_cpp4rtest_findInterval3`, x, breaks)
}

findInterval4 <- function(x, breaks) {
  .Call(`_cpp4rtest_findInterval4`, x, breaks)
}

grow_ <- function(n) {
  .Call(`_cpp4rtest_grow_`, n)
}

grow_cplx_ <- function(n) {
  .Call(`_cpp4rtest_grow_cplx_`, n)
}

cpp4r_insert_ <- function(num_sxp) {
  .Call(`_cpp4rtest_cpp4r_insert_`, num_sxp)
}

ordered_map_to_list_ <- function(x) {
  .Call(`_cpp4rtest_ordered_map_to_list_`, x)
}

unordered_map_to_list_ <- function(x) {
  .Call(`_cpp4rtest_unordered_map_to_list_`, x)
}

gibbs_cpp <- function(N, thin) {
  .Call(`_cpp4rtest_gibbs_cpp`, N, thin)
}

gibbs_cpp2 <- function(N, thin) {
  .Call(`_cpp4rtest_gibbs_cpp2`, N, thin)
}

gibbs_Rcpp <- function(N, thin) {
  .Call(`_cpp4rtest_gibbs_Rcpp`, N, thin)
}

gibbs_Rcpp2 <- function(N, thin) {
  .Call(`_cpp4rtest_gibbs_Rcpp2`, N, thin)
}

row_sums <- function(x) {
  .Call(`_cpp4rtest_row_sums`, x)
}

mat_mat_copy_dimnames <- function(x) {
  .Call(`_cpp4rtest_mat_mat_copy_dimnames`, x)
}

mat_sexp_copy_dimnames <- function(x) {
  .Call(`_cpp4rtest_mat_sexp_copy_dimnames`, x)
}

mat_mat_create_dimnames <- function() {
  .Call(`_cpp4rtest_mat_mat_create_dimnames`)
}

col_sums <- function(x) {
  .Call(`_cpp4rtest_col_sums`, x)
}

protect_one_ <- function(x, n) {
  invisible(.Call(`_cpp4rtest_protect_one_`, x, n))
}

protect_one_sexp_ <- function(x, n) {
  invisible(.Call(`_cpp4rtest_protect_one_sexp_`, x, n))
}

protect_one_cpp4r_ <- function(x, n) {
  invisible(.Call(`_cpp4rtest_protect_one_cpp4r_`, x, n))
}

protect_one_preserve_ <- function(x, n) {
  invisible(.Call(`_cpp4rtest_protect_one_preserve_`, x, n))
}

protect_many_ <- function(n) {
  invisible(.Call(`_cpp4rtest_protect_many_`, n))
}

protect_many_cpp4r_ <- function(n) {
  invisible(.Call(`_cpp4rtest_protect_many_cpp4r_`, n))
}

protect_many_sexp_ <- function(n) {
  invisible(.Call(`_cpp4rtest_protect_many_sexp_`, n))
}

protect_many_preserve_ <- function(n) {
  invisible(.Call(`_cpp4rtest_protect_many_preserve_`, n))
}

protect_many_Rcpp_ <- function(n) {
  invisible(.Call(`_cpp4rtest_protect_many_Rcpp_`, n))
}

cpp4r_release_ <- function(n) {
  invisible(.Call(`_cpp4rtest_cpp4r_release_`, n))
}

Rcpp_release_ <- function(n) {
  invisible(.Call(`_cpp4rtest_Rcpp_release_`, n))
}

notroxcpp1_ <- function(x) {
  .Call(`_cpp4rtest_notroxcpp1_`, x)
}

#' @title Roxygenise C++ function II
#' @param x numeric value
#' @description Dummy function to test roxygen2. It adds 2.0 to a double.
#' @export
#' @examples roxcpp2(1.0)
roxcpp2 <- function(x) {
	.Call(`_cpp4rtest_roxcpp2`, x)
}

#' @title Roxygenise C++ function III
#' @param x numeric value
#' @description Dummy function to test roxygen2. It adds 3.0 to a double.
#' @export
#' @examples roxcpp3(1.0)
roxcpp3 <- function(x) {
	.Call(`_cpp4rtest_roxcpp3`, x)
}

#' @title Roxygenise C++ function IV
#' @param x numeric value
#' @description Dummy function to test roxygen2. It adds 4.0 to a double.
#' @export
#' @examples roxcpp4(1.0)
roxcpp4 <- function(x) {
	.Call(`_cpp4rtest_roxcpp4`, x)
}

#' @title Roxygenise C++ function V
#' @param x numeric value
#' @description Dummy function to test roxygen2. It adds 5.0 to a double.
#' @export
#' @examples roxcpp5(1.0)
roxcpp5 <- function(x) {
	.Call(`_cpp4rtest_roxcpp5`, x)
}

notroxcpp6_ <- function(x) {
  .Call(`_cpp4rtest_notroxcpp6_`, x)
}

#' @title Roxygenise C++ function VII
#' @param x numeric value
#' @description Dummy function to test roxygen2. It adds 7.0 to a double.
#' @export
#' @examples
#' my_fun <- function(x) {
#'   roxcpp7(x)
#' }
#' @seealso \code{\link{roxcpp3}}
roxcpp7 <- function(x) {
	.Call(`_cpp4rtest_roxcpp7`, x)
}

cpp4r_safe_ <- function(x_sxp) {
  .Call(`_cpp4rtest_cpp4r_safe_`, x_sxp)
}

string_proxy_assignment_ <- function() {
  .Call(`_cpp4rtest_string_proxy_assignment_`)
}

string_push_back_ <- function() {
  .Call(`_cpp4rtest_string_push_back_`)
}

grow_strings_cpp4r_ <- function(n, seed) {
  .Call(`_cpp4rtest_grow_strings_cpp4r_`, n, seed)
}

grow_strings_Rcpp_ <- function(n, seed) {
  .Call(`_cpp4rtest_grow_strings_Rcpp_`, n, seed)
}

grow_strings_manual_ <- function(n, seed) {
  .Call(`_cpp4rtest_grow_strings_manual_`, n, seed)
}

assign_cpp4r_ <- function(n, seed) {
  .Call(`_cpp4rtest_assign_cpp4r_`, n, seed)
}

assign_Rcpp_ <- function(n, seed) {
  .Call(`_cpp4rtest_assign_Rcpp_`, n, seed)
}

sum_dbl_for_ <- function(x) {
  .Call(`_cpp4rtest_sum_dbl_for_`, x)
}

sum_dbl_for2_ <- function(x_sxp) {
  .Call(`_cpp4rtest_sum_dbl_for2_`, x_sxp)
}

sum_dbl_for3_ <- function(x_sxp) {
  .Call(`_cpp4rtest_sum_dbl_for3_`, x_sxp)
}

sum_dbl_foreach_ <- function(x) {
  .Call(`_cpp4rtest_sum_dbl_foreach_`, x)
}

sum_dbl_foreach2_ <- function(x_sxp) {
  .Call(`_cpp4rtest_sum_dbl_foreach2_`, x_sxp)
}

sum_dbl_accumulate_ <- function(x) {
  .Call(`_cpp4rtest_sum_dbl_accumulate_`, x)
}

sum_dbl_accumulate2_ <- function(x_sxp) {
  .Call(`_cpp4rtest_sum_dbl_accumulate2_`, x_sxp)
}

sum_cplx_for_ <- function(x) {
  .Call(`_cpp4rtest_sum_cplx_for_`, x)
}

sum_cplx_for_2_ <- function(x) {
  .Call(`_cpp4rtest_sum_cplx_for_2_`, x)
}

sum_cplx_for_3_ <- function(x_sxp) {
  .Call(`_cpp4rtest_sum_cplx_for_3_`, x_sxp)
}

sum_cplx_for_4_ <- function(x_sxp) {
  .Call(`_cpp4rtest_sum_cplx_for_4_`, x_sxp)
}

sum_cplx_for_5_ <- function(x_sxp) {
  .Call(`_cpp4rtest_sum_cplx_for_5_`, x_sxp)
}

sum_cplx_for_6_ <- function(x_sxp) {
  .Call(`_cpp4rtest_sum_cplx_for_6_`, x_sxp)
}

sum_cplx_foreach_ <- function(x) {
  .Call(`_cpp4rtest_sum_cplx_foreach_`, x)
}

sum_cplx_accumulate_ <- function(x) {
  .Call(`_cpp4rtest_sum_cplx_accumulate_`, x)
}

sum_cplx_for2_ <- function(x_sxp) {
  .Call(`_cpp4rtest_sum_cplx_for2_`, x_sxp)
}

Rcpp_sum_dbl_for_ <- function(x_sxp) {
  .Call(`_cpp4rtest_Rcpp_sum_dbl_for_`, x_sxp)
}

Rcpp_sum_int_for_ <- function(x_sxp) {
  .Call(`_cpp4rtest_Rcpp_sum_int_for_`, x_sxp)
}

Rcpp_sum_dbl_foreach_ <- function(x_sxp) {
  .Call(`_cpp4rtest_Rcpp_sum_dbl_foreach_`, x_sxp)
}

Rcpp_sum_dbl_accumulate_ <- function(x_sxp) {
  .Call(`_cpp4rtest_Rcpp_sum_dbl_accumulate_`, x_sxp)
}

Rcpp_grow_ <- function(n_sxp) {
  .Call(`_cpp4rtest_Rcpp_grow_`, n_sxp)
}

Rcpp_push_and_truncate_ <- function(size_sxp) {
  .Call(`_cpp4rtest_Rcpp_push_and_truncate_`, size_sxp)
}

sum_int_for_ <- function(x) {
  .Call(`_cpp4rtest_sum_int_for_`, x)
}

sum_int_for2_ <- function(x_) {
  .Call(`_cpp4rtest_sum_int_for2_`, x_)
}

sum_int_foreach_ <- function(x) {
  .Call(`_cpp4rtest_sum_int_foreach_`, x)
}

sum_int_accumulate_ <- function(x) {
  .Call(`_cpp4rtest_sum_int_accumulate_`, x)
}

nullable_extptr_1 <- function() {
  .Call(`_cpp4rtest_nullable_extptr_1`)
}

nullable_extptr_2 <- function() {
  .Call(`_cpp4rtest_nullable_extptr_2`)
}

test_destruction_inner <- function() {
  invisible(.Call(`_cpp4rtest_test_destruction_inner`))
}

test_destruction_outer <- function() {
  invisible(.Call(`_cpp4rtest_test_destruction_outer`))
}

cpp4r_push_and_truncate_ <- function(size_sexp) {
  .Call(`_cpp4rtest_cpp4r_push_and_truncate_`, size_sexp)
}
