# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rejection_sampling_Rcpp_ <- function(n_samples, mu = 0.0, sigma = 1.0, lower = -2.0, upper = 2.0) {
    .Call(`_Rcppsampling_rejection_sampling_Rcpp_`, n_samples, mu, sigma, lower, upper)
}

bootstrap_variable_Rcpp_ <- function(data, min_size, max_size, n_bootstrap) {
    .Call(`_Rcppsampling_bootstrap_variable_Rcpp_`, data, min_size, max_size, n_bootstrap)
}

