# Generated by cpp4r: do not edit by hand

#' @title Rejection Sampling from Truncated Normal Distribution
#' @description Demonstrates dynamic vector growth with rejection sampling - you don't know 
#'   how many samples you need to generate to get n_samples accepted values
#' @param n_samples Number of accepted samples desired
#' @param mu Mean of the normal distribution
#' @param sigma Standard deviation of the normal distribution  
#' @param lower Lower truncation bound
#' @param upper Upper truncation bound
#' @export
rejection_sampling_cpp4r <- function(n_samples, mu, sigma, lower, upper) {
	.Call(`_cpp4rsampling_rejection_sampling_cpp4r`, n_samples, mu, sigma, lower, upper)
}

#' @title Bootstrap Resampling with Variable Sample Sizes
#' @description Another natural use case for push_back - bootstrap sampling where
#'   sample sizes can vary based on some condition
#' @param data Original data vector
#' @param min_size Minimum bootstrap sample size
#' @param max_size Maximum bootstrap sample size  
#' @param n_bootstrap Number of bootstrap samples
#' @export
bootstrap_variable_cpp4r <- function(data, min_size, max_size, n_bootstrap) {
	.Call(`_cpp4rsampling_bootstrap_variable_cpp4r`, data, min_size, max_size, n_bootstrap)
}
