# Generated by cpp11: do not edit by hand

rejection_sampling_cpp11_ <- function(n_samples, mu, sigma, lower, upper) {
  .Call(`_cpp11sampling_rejection_sampling_cpp11_`, n_samples, mu, sigma, lower, upper)
}

bootstrap_variable_cpp11_ <- function(data, min_size, max_size, n_bootstrap) {
  .Call(`_cpp11sampling_bootstrap_variable_cpp11_`, data, min_size, max_size, n_bootstrap)
}
